spring:
  kafka:
    producer:
      bootstrap-servers: kafka:29092
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    consumer:
      bootstrap-servers: kafka:29092
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  datasource:
    url: jdbc:mysql://mysql:3306/mydatabase?useSSL=false
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  restart:
    exclude:
      company-classes=/com/andrei/labbinary/avro/:
